name: test
on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  create-release:

    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo $GITHUB_WORKSPACE